### ISSUE TITLE
Update es6-module-transpiler dependency

### ISSUE THREAD

**Issue by LyhjeHylje** [shama/es6-loader#7]
I am trying to solve error which (I believe) is caused by es6-loader using old version of es6-module-transpiler which (in version 0.4.0) uses buggy version of es6ify.
(https://github.com/esnext/es6-module-transpiler/issues/128)

I got the error while trying to set up karma to work with the same webpack settings as my build system.

**Comment by demisx** [comment]
+1

**Comment by Bartvds** [comment]
+1

**Comment by bobbyrenwick** [comment]
+1

**Comment by volkanunsal** [comment]
Same here. Also, the module transpiler is not picking up generator syntax for me.

**Comment by tomatau** [comment]
switched to https://github.com/6to5/6to5-loader, more recent and active

**Comment by volkanunsal** [comment]
You rock @tomatau!

**Comment by shama** [comment]
Any objections to me deprecating this lib in favor of 6to5-loader?

**Comment by bobbyrenwick** [comment]
Great suggestion @tomatau! @shama no objections from me.

**Comment by tomatau** [comment]
There's also https://www.npmjs.com/package/traceur-loader that works fine too. Happy for this to be deprecated

**Comment by LyhjeHylje** [comment]
No objections from me either. 
Alternatives suggested by @tomatau looks good, thanks.
